export { Telegram } from './Telegram'
export type { TelegramProps } from './Telegram'
export { Newspaper } from './Newspaper'
export type { NewspaperProps } from './Newspaper'
export { MapDocument } from './MapDocument'
export type { MapDocumentProps } from './MapDocument'
